logging:
  level: INFO
  loggers:
    io.dropwizard: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 7000
  adminConnectors:
    - type: http
      port: 7001

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  url: jdbc:mysql://localhost:3306/Split_APP
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true